import type { GlobalConfig } from 'payload'

export const LocationPage: GlobalConfig = {
  slug: 'location-page',
  label: 'Location Page',
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'heroSection',
      type: 'group',
      label: 'Hero Section',
      fields: [
        {
          name: 'isActive',
          type: 'checkbox',
          label: 'Show Hero Section',
          defaultValue: true,
        },
        {
          name: 'mainTitleRo',
          type: 'text',
          label: 'Main Title (Romanian)',
          required: true,
          defaultValue: 'Localizare Ansamblul Rezidential Briza4Seasons',
        },
        {
          name: 'mainTitleEn',
          type: 'text',
          label: 'Main Title (English)',
          required: true,
          defaultValue: 'Location of Briza4Seasons Residential Complex',
        },
        {
          name: 'mainTitleHe',
          type: 'text',
          label: 'Main Title (Hebrew)',
          required: true,
          defaultValue: 'מיקום מתחם המגורים ברייזה4עונות',
        },
        {
          name: 'subtitleRo',
          type: 'text',
          label: 'Subtitle (Romanian)',
          required: true,
          defaultValue: 'UNDE NE GĂSIȚI?',
        },
        {
          name: 'subtitleEn',
          type: 'text',
          label: 'Subtitle (English)',
          required: true,
          defaultValue: 'WHERE TO FIND US?',
        },
        {
          name: 'subtitleHe',
          type: 'text',
          label: 'Subtitle (Hebrew)',
          required: true,
          defaultValue: 'איפה אתם יכולים למצוא אותנו',
        },
        {
          name: 'backgroundImage',
          type: 'upload',
          relationTo: 'media',
          label: 'Background Image',
          required: true,
        },
        {
          name: 'breadcrumbs',
          type: 'array',
          label: 'Breadcrumbs',
          minRows: 1,
          maxRows: 5,
          fields: [
            {
              name: 'labelRo',
              type: 'text',
              label: 'Label (Romanian)',
              required: true,
            },
            {
              name: 'labelEn',
              type: 'text',
              label: 'Label (English)',
              required: true,
            },
            {
              name: 'labelHe',
              type: 'text',
              label: 'Label (Hebrew)',
              required: true,
            },
            {
              name: 'href',
              type: 'text',
              label: 'Link URL',
              required: true,
            },
            {
              name: 'isActive',
              type: 'checkbox',
              label: 'Is Active Page',
              defaultValue: false,
            },
          ],
          defaultValue: [
            {
              labelRo: 'Acasă',
              labelEn: 'Home',
              labelHe: 'בית',
              href: '/',
              isActive: false,
            },
            {
              labelRo: 'Locație',
              labelEn: 'Location',
              labelHe: 'מיקום',
              href: '/location',
              isActive: true,
            },
          ],
        },
      ],
    },
    {
      name: 'locationMapSection',
      type: 'group',
      label: 'Location Map Section',
      fields: [
        {
          name: 'isActive',
          type: 'checkbox',
          label: 'Show Location Map Section',
          defaultValue: true,
        },
        {
          name: 'sectionTitleRo',
          type: 'text',
          label: 'Section Title (Romanian)',
          required: true,
          defaultValue: 'Localizare Ansamblul',
        },
        {
          name: 'sectionTitleEn',
          type: 'text',
          label: 'Section Title (English)',
          required: true,
          defaultValue: 'Complex Location',
        },
        {
          name: 'sectionTitleHe',
          type: 'text',
          label: 'Section Title (Hebrew)',
          required: true,
          defaultValue: 'מיקום המתחם',
        },
        {
          name: 'sectionSubtitleRo',
          type: 'text',
          label: 'Section Subtitle (Romanian)',
          required: true,
          defaultValue: 'Unde ne găsiți?',
        },
        {
          name: 'sectionSubtitleEn',
          type: 'text',
          label: 'Section Subtitle (English)',
          required: true,
          defaultValue: 'Where can you find us?',
        },
        {
          name: 'sectionSubtitleHe',
          type: 'text',
          label: 'Section Subtitle (Hebrew)',
          required: true,
          defaultValue: 'איפה אתם יכולים למצוא אותנו',
        },
        {
          name: 'sectionDescriptionRo',
          type: 'textarea',
          label: 'Section Description (Romanian)',
          required: true,
          defaultValue:
            'Proiectul rezidențial Briza4Seasons este situat în Otopeni, într-o zonă liniștită, verde și sigură, la doar câteva minute de Nordul Bucureștiului. Locația oferă acces facil către DN1, Aeroportul Henri Coandă, școli internaționale, clinici private și principalele centre de business din Pipera, Băneasa și Aviației. Find poziționat strategic, Briza4Seasons combină avantajele locuirii în proximitatea orașului cu liniștea unei comunități rezidențiale exclusiviste.',
        },
        {
          name: 'sectionDescriptionEn',
          type: 'textarea',
          label: 'Section Description (English)',
          required: true,
          defaultValue:
            'The Briza4Seasons residential complex is located in Otopeni, in a quiet, green, and safe area just minutes away from the northern part of Bucharest. The location offers easy access to DN1, Henri Coandă International Airport, international schools, private clinics, and major business hubs in Pipera, Băneasa, and Aviației. Strategically positioned, Briza4Seasons combines the advantages of living close to the city with the peace and privacy of an exclusive residential community.',
        },
        {
          name: 'sectionDescriptionHe',
          type: 'textarea',
          label: 'Section Description (Hebrew)',
          required: true,
          defaultValue:
            'מתחם המגורים ברייזה4עונות ממוקם באוטופני, באזור שקט, ירוק ובטוח, רק דקות ספורות מצפון בוקרשט. המיקום מציע גישה נוחה לכביש DN1, נמל התעופה הבינלאומי אנרי קואנדה, בתי ספר בינלאומיים, מרפאות פרטיות ומרכזי העסקים הראשיים בפיפרה, באנאסה ואביאציה. ממוקם אסטרטגית, ברייזה4עונות משלב את היתרונות של מגורים קרוב לעיר עם השלווה והפרטיות של קהילת מגורים אקסקלוסיבית.',
        },
        {
          name: 'mapEmbedUrl',
          type: 'text',
          label: 'Google Maps Embed URL',
          required: true,
          defaultValue:
            'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2843.5!2d26.0826!3d44.5675!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40b1ff4770b5b5b5%3A0x5!2s23%20August%2C%20Otopeni%2C%20Ilfov%2C%20Romania!5e0!3m2!1sen!2sro!4v1642684800000!5m2!1sen!2sro',
        },
        {
          name: 'address',
          type: 'text',
          label: 'Address',
          required: true,
          defaultValue: 'Intrarea Mesteacănului, Otopeni, București / Ilfov',
        },
        {
          name: 'locationPoints',
          type: 'array',
          label: 'Location Points',
          minRows: 1,
          fields: [
            {
              name: 'nameRo',
              type: 'text',
              label: 'Name (Romanian)',
              required: true,
            },
            {
              name: 'nameEn',
              type: 'text',
              label: 'Name (English)',
              required: true,
            },
            {
              name: 'nameHe',
              type: 'text',
              label: 'Name (Hebrew)',
              required: true,
            },
            {
              name: 'distance',
              type: 'text',
              label: 'Distance',
              required: true,
            },
            {
              name: 'category',
              type: 'select',
              label: 'Category',
              required: true,
              options: [
                { label: 'Shopping', value: 'shopping' },
                { label: 'Education', value: 'education' },
                { label: 'Transport', value: 'transport' },
                { label: 'Retail', value: 'retail' },
                { label: 'Other', value: 'other' },
              ],
              defaultValue: 'other',
            },
            {
              name: 'order',
              type: 'number',
              label: 'Display Order',
              defaultValue: 0,
            },
          ],
          defaultValue: [
            {
              nameRo: 'Aeroportul International Henri Coandă',
              nameEn: 'Henri Coandă International Airport',
              nameHe: 'נמל התעופה הבינלאומי אנרי קואנדה',
              distance: '5 km',
              category: 'transport',
              order: 1,
            },
            {
              nameRo: 'Zona de business Pipera',
              nameEn: 'Pipera Business District',
              nameHe: 'מרכז העסקים פיפרה (Pipera)',
              distance: '10 km',
              category: 'other',
              order: 2,
            },
            {
              nameRo: 'Băneasa Shopping City',
              nameEn: 'Băneasa Shopping City',
              nameHe: 'בנאסה קניון באנאסה (Băneasa Shopping City)',
              distance: '8 km',
              category: 'shopping',
              order: 3,
            },
            {
              nameRo: 'Pădurea Băneasa / Parcul Herăstrău',
              nameEn: 'Băneasa Forest / King Michael I Park (Herăstrău)',
              nameHe: 'יער באנאסה / פארק המלך מיכאל הראשון (הרסטראו)',
              distance: '9 km',
              category: 'other',
              order: 4,
            },
            {
              nameRo: 'DN1 & Centura Bucureștiului',
              nameEn: 'DN1 & Bucharest Ring Road',
              nameHe: 'כביש הטבעת של בוקרשט DN1 כביש',
              distance: '3 km',
              category: 'transport',
              order: 5,
            },
          ],
        },
        {
          name: 'ctaButtonTextRo',
          type: 'text',
          label: 'CTA Button Text (Romanian)',
          required: true,
          defaultValue: 'AFLAȚI MAI MULTE',
        },
        {
          name: 'ctaButtonTextEn',
          type: 'text',
          label: 'CTA Button Text (English)',
          required: true,
          defaultValue: 'FIND OUT MORE',
        },
        {
          name: 'ctaButtonTextHe',
          type: 'text',
          label: 'CTA Button Text (Hebrew)',
          required: true,
          defaultValue: 'גלו עוד',
        },
        {
          name: 'ctaDescriptionRo',
          type: 'textarea',
          label: 'CTA Description (Romanian)',
          required: true,
          defaultValue:
            'Pentru a vă ajuta să vă orientați mai bine în zonă, iată câteva zone importante la care puteți ajunge cu ușurință cu mașina din Otopeni în mai puțin de 10 km:',
        },
        {
          name: 'ctaDescriptionEn',
          type: 'textarea',
          label: 'CTA Description (English)',
          required: true,
          defaultValue:
            'To help you navigate the area better, here are some important areas you can easily reach by car from Tunari in less than 10 km:',
        },
        {
          name: 'ctaDescriptionHe',
          type: 'textarea',
          label: 'CTA Description (Hebrew)',
          required: true,
          defaultValue:
            'כדי לעזור לכם להתמצא טוב יותר באזור, הנה כמה אזורים חשובים שתוכלו להגיע אליהם בקלות ברכב מטונארי בפחות מ-10 ק"מ:',
        },
      ],
    },
  ],
}
